### ISSUE TITLE
Code coverage and GitHub Actions pipeline

### ISSUE THREAD

**Issue by tnishamon** [UNLV-CS472-672/2024-S-GROUP2-2DRove#30]
We need to implement our GitHub workflow pipeline as specified for the class. I am going to be working off a branch of mapgen, and then pivot to the additions needed on main and integrate it for everyone's main branch.

**Comment by tnishamon** [comment]
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP2-2DRove/assets/92564751/2ad4491e-50b7-476f-9102-cf8b75eed05a)

![image](https://github.com/UNLV-CS472-672/2024-S-GROUP2-2DRove/assets/92564751/4a713bff-5ba8-4df1-969e-7e9ec25f5f1c)

I have generated Code Coverage and the binaries and stuff I need to run tests works!

**Comment by tnishamon** [comment]
TODO: Work on CodeEnv integration on my fork and figure out how to write tests for our stuff. 

![image](https://github.com/UNLV-CS472-672/2024-S-GROUP2-2DRove/assets/92564751/ffb80c0c-f8a1-4170-96c2-61b19b52840e)

Right now the tests written are empty, I just wanted to see how things would look and if they work.

**Comment by koyomi7** [comment]
Thanks for your tutorial on the test coverage procedure

**Comment by tnishamon** [comment]
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP2-2DRove/assets/92564751/b280d9d3-273b-49df-a6db-ae7515775e57)
Pipeline has been implemented on a branch of main. Will merge once I check about fixing issues with the pipeline tests failing.

**Comment by Intensifiesx** [comment]
I'll see if I can get more code coverage with the latest push.

**Comment by SwiftNemesis** [comment]
Leaving issue open if it's further needed, otherwise please close @tnishamon
