### ISSUE TITLE
Spitter's ranged attack missing 

### ISSUE THREAD

**Issue by koyomi7** [UNLV-CS472-672/2024-S-GROUP2-2DRove#35]
Spitter is supposed to have ranged attack, now it only functions as a melee mob. Need to fix that after this week's due done

**Comment by YordyCruz** [comment]
I'm updating the Spitter to have a ranged attack and its complete state machine, I will push the fix by tonight. Thanks for the feedback!

**Comment by koyomi7** [comment]
> I'm updating the Spitter to have a ranged attack and its complete state machine, I will push the fix by tonight. Thanks for the feedback!

I have a TestEnemyProjectile prefab save in prefab folder, its something i did a while back on my demo, it allows the TestEnemyDummies to shoot out projectile, just thought u could reference it if you need, just an FYI! Thanks for the good work always
