### ISSUE TITLE
Initial Augment System Creation

### ISSUE THREAD

**Issue by SwiftNemesis** [UNLV-CS472-672/2024-S-GROUP2-2DRove#74]
As the title says, we want to create an augment system that a player can gain at the end of a floor or after defeating a boss which will allow the player to grow heavily in power and be able to augment their character with new effects.

NOTE: These are generated by **ChatGPT**, but this can help us get started on ideas.

- [ ] Vampiric Touch: Melee attacks steal health from enemies.
- [ ] Invisibility Cloak: Grants temporary invisibility, allowing the player to bypass enemies unnoticed.
- [ ] Phoenix Rebirth: Automatically resurrects the player upon death with full health, but can only be used once per run.
- [ ] Temporal Shift: Slows down time for enemies, giving the player a significant advantage in combat.
- [ ] Ethereal Form: Allows the player to pass through walls and obstacles for a limited duration.
- [ ] Berserker Rage: Boosts damage output for a short period, but also increases damage taken.
- [ ] Teleportation: Instantly teleport to a chosen location within the player's line of sight.
- [ ] Elemental Mastery: Grants immunity to a specific element (fire, ice, electricity, etc.) for a short time.
- [ ] Echoes of the Past: Creates ghostly clones of the player to distract enemies and absorb damage.
- [ ] Mind Control: Temporarily takes control of an enemy, making them fight on the player's side.
- [ ] Aegis Shield: Creates a protective barrier that absorbs a certain amount of damage before breaking.
- [ ] Toxic Cloud: Releases a poisonous gas cloud upon taking damage, damaging nearby enemies.
- [ ] Spectral Blades: Summons floating swords to attack enemies automatically for a limited time.
- [ ] Gravity Manipulation: Allows the player to control the gravity around them, affecting movement and enemies.
- [ ] Siphon Energy: Drains enemy energy to replenish the player's health or mana.
- [ ] Shadow Step: Teleports the player behind the targeted enemy, granting a surprise attack.
- [ ] Petrifying Gaze: Stuns enemies within the player's line of sight for a short duration.
- [ ] Chaos Infusion: Randomly alters enemy behavior or environment conditions for a short time.
- [ ] Frost Nova: Freezes all nearby enemies upon activation.
- [ ] Divine Intervention: Summons a powerful celestial entity to aid the player in battle for a limited time.

**Comment by SwiftNemesis** [comment]
Please comment ideas for the augment system.

**Comment by YordyCruz** [comment]
I like the following augments:
* Temporal Shift: Slows down time for enemies, giving the player a significant advantage in combat.
 * Berserker Rage: Boosts damage output for a short period, but also increases damage taken.
 * Invisibility Cloak: Grants temporary invisibility, allowing the player to bypass enemies unnoticed.
 *  Teleportation: Instantly teleport to a chosen location within the player's line of sight.
 
I believe this 4 augment can be implemented, they will create different play styles and help the player to beat the game. 

- Note: We will need to set rules to some augments so they are not game breaking.

**Comment by koyomi7** [comment]
These are some BIG buffs, I think we can add small buffs that come with them, like stats increase(health/mana), slowly regenerate health/mana/stamina, regen health on kill, etc...

**Comment by AlphabetWolf** [comment]
I like those augments:
- Vampiric Touch: Melee attacks steal health from enemies.
- Phoenix Rebirth: Automatically resurrects the player upon death with full health, but can only be used once per run.
- Aegis Shield: Creates a protective barrier that absorbs a certain amount of damage before breaking.

I also thought of some interesting augments:
- Melee Elite: Players can't use ranged attacks, but melee damage is boosted by [num]%.
- Stop Watch: Stop Watch is just like League of Legends's Stop Watch.

**Comment by SwiftNemesis** [comment]
Thank you for the ideas. I'm going to go ahead and make a PR to fsmtest once I get the actual prefab for the augment canvas made and just have an initial implementation that currently won't affect any stats. I'll make a 2nd PR that will be larger and go through and implement a set of some smaller/larger powered augments and if anyone wants to help me with that, I may need some guidance on affecting player stats etc.
