### ISSUE TITLE
Implement isoTiles

### ISSUE THREAD

**Issue by SwiftNemesis** [UNLV-CS472-672/2024-S-GROUP2-2DRove#8]
As the title says.

## Instructions:

Implement IsoTiles into a mapgen and change the camera view/angle of the map generation in order to implement it.

In terms of way of implementing it, that will be up to the issue taker.

## Suggestions:
- Tilt the camera
- Make sure mapgen works on an angled camera view access of the plane
- Implement the asset (Assets will be purchased and are in the mapgen channel)

## Assets:
- https://assetstore.unity.com/packages/2d/environments/isotile-universe-245686

**Comment by Intensifiesx** [comment]
I would like to test what camera angles work the best
