### ISSUE TITLE
Ruined City

### ISSUE THREAD

**Issue by Haikp** [UNLV-CS472-672/2024-S-GROUP2-2DRove#91]
You will be creating tile prefabs that can fit well with this theme. You will need to generate code that is able to utilize the generation algorithm, and put the prefabs in the correct spot/orientation. You only need to worry about generating the map itself and the aesthetic, do not worry about generating mobs/the portal/entrance/etc.

Isometric Tiles:
https://assetstore.unity.com/packages/2d/environments/isotile-universe-245686

Themes to reference/use if needed:
https://penusbmic.itch.io/the-dark-series-victorian-style-add-on
https://penusbmic.itch.io/the-dark-series-victorian-parallax-city
https://penusbmic.itch.io/the-dark-series-beneath-tileset

Mobs:
https://penusbmic.itch.io/the-dark-series-enemy-pack-6
Caged Shocker
The Dark Warden
Caged Spider

Boss:
https://penusbmic.itch.io/the-dark-series-the-temple-guardians
GuardianBoss

**Comment by fergut3** [comment]
I'll go ahead and start working on designing that level.
